# Generated by Django 4.0.5 on 2022-08-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_subcatgeory_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='user_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcatgeory',
            new_name='subcategory',
        ),
    ]
